import type {
  Hero,
  Company,
  Producer,
  Job,
  Sponsor,
  PendingVerification,
  AdminReport,
} from "./types";

export const sampleHeroes: Hero[] = [
  {
    id: "h1",
    socials: { github: "https://github.com/m-asiri", x: "https://x.com/m_asiri", linkedin: "https://linkedin.com/in/m-asiri", website: "https://masiri.dev" },
    name: "محمد عسيري",
    title: "مطوّر واجهات أمامية",
    city: "صبيا",
    status: "freelance",
    skills: ["React", "TypeScript", "Next.js", "RTL"],
    years: 4,
    rating: 4.9,
    reviewsCount: 12,
    verified: true,
    whatsapp: "966500000101",
    bio: "مطوّر واجهات أمامية بخبرة 4 سنوات في React وTypeScript، يركّز على الأداء وتجربة المستخدم وبناء واجهات عربية الاتجاه.",
    reviews: [
      {
        id: "rv1",
        author: "تهامة للتقنية",
        rating: 5,
        comment: "تسليم قبل الموعد وجودة عالية في التفاصيل. تجربة تعامل ممتازة.",
        date: "قبل أسبوع",
      },
      {
        id: "rv2",
        author: "متجر الساحل",
        rating: 5,
        comment: "طوّر لنا واجهة المتجر بالكامل — سريع، متعاون، ويقترح حلولاً أفضل.",
        date: "قبل شهر",
      },
      {
        id: "rv3",
        author: "واحة جازان الرقمية",
        rating: 4,
        comment: "عمل احترافي والتواصل سلس عبر واتساب.",
        date: "قبل شهرين",
      },
    ],
  },
  {
    id: "h2",
    socials: { instagram: "https://instagram.com/noura.design", x: "https://x.com/noura_hakami", linkedin: "https://linkedin.com/in/noura-hakami" },
    name: "نورة حكمي",
    title: "مصمّمة هوية بصرية",
    city: "جيزان",
    status: "both",
    skills: ["هوية بصرية", "Figma", "تصميم"],
    years: 3,
    rating: 5.0,
    reviewsCount: 8,
    verified: true,
    whatsapp: "966500000102",
    reviews: [
      {
        id: "rv4",
        author: "دار صبيا للنشر",
        rating: 5,
        comment: "صمّمت هوية كاملة لمشروعنا — ذوق رفيع وفهم عميق للسوق المحلي.",
        date: "قبل أسبوعين",
      },
      {
        id: "rv5",
        author: "أسرة نكهات صبيا",
        rating: 5,
        comment: "شعارنا الجديد من إبداعها. شكراً نورة!",
        date: "قبل شهر",
      },
    ],
  },
  {
    id: "h3",
    socials: { linkedin: "https://linkedin.com/in/a-malki", github: "https://github.com/a-malki", x: "https://x.com/a_malki" },
    name: "عبدالله مالكي",
    title: "مهندس بيانات",
    city: "أبو عريش",
    status: "job",
    skills: ["Python", "SQL", "تحليل بيانات"],
    years: 4,
    rating: 4.7,
    reviewsCount: 5,
    whatsapp: "966500000103",
  },
  {
    id: "h4",
    socials: { x: "https://x.com/reem_writes", linkedin: "https://linkedin.com/in/reem-zailai", website: "https://reemwrites.sa" },
    name: "ريم زيلعي",
    title: "كاتبة محتوى",
    city: "جيزان",
    status: "freelance",
    skills: ["كتابة", "SEO"],
    years: 2,
    rating: 4.8,
    reviewsCount: 9,
    whatsapp: "966500000104",
  },
  {
    id: "h5",
    socials: { instagram: "https://instagram.com/khaled.lens", youtube: "https://youtube.com/@khaledlens", tiktok: "https://tiktok.com/@khaled.lens" },
    name: "خالد فيفي",
    title: "مصوّر فوتوغرافي",
    city: "فيفا",
    status: "both",
    skills: ["تصوير", "مونتاج"],
    years: 5,
    rating: 4.9,
    reviewsCount: 16,
    whatsapp: "966500000105",
    reviews: [
      {
        id: "rv6",
        author: "واحة جازان الرقمية",
        rating: 5,
        comment: "تصوير احترافي لحملتنا الإعلانية — زوايا مبدعة وإخراج مميز.",
        date: "قبل 3 أيام",
      },
    ],
  },
  {
    id: "h6",
    socials: { github: "https://github.com/sara-madkhali", linkedin: "https://linkedin.com/in/sara-madkhali" },
    name: "سارة مدخلي",
    title: "مطوّرة واجهات",
    city: "صامطة",
    status: "job",
    skills: ["Vue", "CSS"],
    years: 1,
    rating: 4.6,
    reviewsCount: 4,
    whatsapp: "966500000106",
  },
  {
    id: "h7",
    socials: { github: "https://github.com/y-najmi", x: "https://x.com/y_najmi", youtube: "https://youtube.com/@ynajmi" },
    name: "يوسف نجمي",
    title: "مطوّر تطبيقات",
    city: "بيش",
    status: "freelance",
    skills: ["Flutter", "Firebase"],
    years: 3,
    rating: 4.8,
    reviewsCount: 11,
    whatsapp: "966500000107",
  },
  {
    id: "h8",
    socials: { linkedin: "https://linkedin.com/in/amal-shuabi", x: "https://x.com/amal_shuabi" },
    name: "أمل شعبي",
    title: "مديرة مشاريع",
    city: "الدرب",
    status: "both",
    skills: ["Agile", "Scrum"],
    years: 6,
    rating: 5.0,
    reviewsCount: 20,
    whatsapp: "966500000108",
  },
];

export const producers: Producer[] = [
  {
    id: "pr1",
    socials: { instagram: "https://instagram.com/nakhat.sabya", tiktok: "https://tiktok.com/@nakhat.sabya", whatsapp: "https://wa.me/966500000201" },
    name: "أسرة نكهات صبيا",
    category: "طعام",
    city: "صبيا",
    rating: 4.9,
    reviewsCount: 34,
    verified: true,
    whatsapp: "966500000201",
    bio: "أكلات جازانية منزلية أصيلة — معصوب، مراصيع، وحلويات شعبية بنكهة البيت.",
    products: [
      { id: "p1", name: "معصوب بالموز والعسل", price: 28, category: "طعام" },
      { id: "p2", name: "مرسة جمبري", price: 45, category: "طعام" },
      { id: "p3", name: "عريكة بالعسل البلدي", price: 35, category: "طعام" },
      { id: "p4", name: "مديد الحلبة", price: 22, category: "طعام" },
      { id: "p5", name: "رز كبسة دجاج", price: 40, category: "طعام" },
      { id: "p6", name: "حنيذ لحم بلدي", price: 75, category: "طعام" },
    ],
  },
  {
    id: "pr2",
    socials: { instagram: "https://instagram.com/herfat.jazan", x: "https://x.com/herfat_jazan" },
    name: "حرفة جازان",
    category: "حِرف",
    city: "أبو عريش",
    rating: 4.8,
    reviewsCount: 21,
    verified: true,
    whatsapp: "966500000202",
    bio: "حِرف يدوية وسلال خوص ومنتجات تراثية مصنوعة بحب.",
    products: [
      { id: "p7", name: "سلة خوص مضفورة يدوياً", price: 60, category: "حِرف" },
      { id: "p8", name: "مكبّة عريش تراثية", price: 85, category: "حِرف" },
      { id: "p9", name: "حصيرة سعف ملوّنة", price: 120, category: "حِرف" },
      { id: "p10", name: "قبعة مظلّة جازانية", price: 45, category: "حِرف" },
      { id: "p11", name: "مروحة يدوية من الخوص", price: 25, category: "حِرف" },
    ],
  },
  {
    id: "pr3",
    socials: { instagram: "https://instagram.com/oud.sahel", youtube: "https://youtube.com/@oudsahel" },
    name: "عطور الساحل",
    category: "عطور",
    city: "جيزان",
    rating: 4.7,
    reviewsCount: 18,
    verified: false,
    whatsapp: "966500000203",
    bio: "عطور ومباخر فاخرة بخلطات جنوبية مميّزة.",
    products: [
      { id: "p12", name: "دهن عود جنوبي فاخر", price: 150, category: "عطور" },
      { id: "p13", name: "خلطة الفل والكادي", price: 95, category: "عطور" },
      { id: "p14", name: "بخور معطّر بالمسك", price: 70, category: "عطور" },
      { id: "p15", name: "ماء ورد طبيعي", price: 35, category: "عطور" },
    ],
  },
];

export const companies: Company[] = [
  {
    id: "c1",
    socials: { x: "https://x.com/tihama_tech", linkedin: "https://linkedin.com/company/tihama-tech", website: "https://tihama.tech" },
    name: "تهامة للتقنية",
    field: "تطوير برمجيات",
    city: "جيزان",
    openings: 4,
    verified: true,
    whatsapp: "966500000301",
    about: "شركة تقنية محلية متخصصة في تطوير البرمجيات والحلول الرقمية لمنطقة جازان.",
  },
  {
    id: "c2",
    socials: { x: "https://x.com/jazan_oasis", instagram: "https://instagram.com/jazan.oasis" },
    name: "واحة جازان الرقمية",
    field: "تسويق رقمي",
    city: "صبيا",
    openings: 3,
    verified: true,
    whatsapp: "966500000302",
  },
  {
    id: "c3",
    socials: { instagram: "https://instagram.com/sahel.store", tiktok: "https://tiktok.com/@sahel.store", website: "https://sahelstore.sa" },
    name: "متجر الساحل",
    field: "تجارة إلكترونية",
    city: "جيزان",
    openings: 2,
    verified: true,
    whatsapp: "966500000303",
  },
  {
    id: "c4",
    socials: { x: "https://x.com/dar_sabya", website: "https://darsabya.sa" },
    name: "دار صبيا للنشر",
    field: "إعلام ومحتوى",
    city: "صبيا",
    openings: 1,
    verified: true,
    whatsapp: "966500000304",
  },
];

export const jobs: Job[] = [
  {
    id: "j1",
    title: "مطوّر واجهات أمامية",
    companyName: "تهامة للتقنية",
    companyId: "c1",
    city: "جيزان",
    type: "دوام كامل",
    salary: "8,000 – 12,000 ر.س",
    tags: ["React", "TypeScript"],
  },
  {
    id: "j2",
    title: "أخصائي تسويق رقمي",
    companyName: "واحة جازان الرقمية",
    companyId: "c2",
    city: "صبيا",
    type: "عن بُعد",
    salary: "6,000 – 9,000 ر.س",
    tags: ["SEO", "إعلانات"],
  },
  {
    id: "j3",
    title: "مدير متجر إلكتروني",
    companyName: "متجر الساحل",
    companyId: "c3",
    city: "جيزان",
    type: "دوام جزئي",
    salary: "بالاتفاق",
    tags: ["إدارة", "تجارة"],
  },
];

export function getHero(id: string): Hero | undefined {
  return sampleHeroes.find((h) => h.id === id);
}

export function getProducer(id: string): Producer | undefined {
  return producers.find((p) => p.id === id);
}

export function getCompany(id: string): Company | undefined {
  return companies.find((c) => c.id === id);
}

export const sponsors: Sponsor[] = [
  { id: "s1", name: "راعٍ ١" },
  { id: "s2", name: "راعٍ ٢" },
  { id: "s3", name: "راعٍ ٣" },
  { id: "s4", name: "راعٍ ٤" },
  { id: "s5", name: "راعٍ ٥" },
];

export const pendingVerifications: PendingVerification[] = [
  { id: "pv1", name: "سعيد قحطاني", role: "hero", city: "جيزان", date: "قبل ساعتين" },
  { id: "pv2", name: "مخبز ريف جازان", role: "producer", city: "بيش", date: "قبل 4 ساعات" },
  { id: "pv3", name: "متجر الساحل", role: "company", city: "جيزان", date: "أمس" },
  { id: "pv4", name: "هند صبياني", role: "hero", city: "صامطة", date: "أمس" },
  { id: "pv5", name: "عطور الساحل", role: "producer", city: "جيزان", date: "قبل يومين" },
  { id: "pv6", name: "تهامة للتقنية", role: "company", city: "جيزان", date: "قبل 3 أيام" },
];

export function getPendingVerification(id: string): PendingVerification | undefined {
  return pendingVerifications.find((p) => p.id === id);
}

export const reports: AdminReport[] = [
  {
    id: "r1",
    target: "متجر الساحل",
    targetType: "شركة",
    targetHref: "/companies/c3",
    reason: "محتوى غير مناسب",
    reporter: "مستخدم #1042",
    date: "اليوم",
    status: "open",
    message: "وصف الشركة يحتوي عبارات دعائية مبالغ فيها وغير لائقة، وتظهر في نتائج البحث بشكل مزعج. أرجو مراجعتها.",
    content: "«أفضل متجر في المملكة بلا منازع — الباقي كلهم مقلّدين، لا تشتري إلا من عندنا!»",
  },
  {
    id: "r2",
    target: "سعيد قحطاني",
    targetType: "بطل / مستقل",
    reason: "معلومات مضلّلة",
    reporter: "مستخدم #877",
    date: "أمس",
    status: "open",
    message: "الملف يدّعي خبرة ١٠ سنوات وشهادات دولية، وبعد التعامل معه اتضح أن الأعمال المعروضة منسوخة من مواقع أجنبية.",
    content: "«خبرة تزيد عن ١٠ سنوات في تطوير التطبيقات، حاصل على شهادات دولية متعددة، ونفّذت أكثر من ٢٠٠ مشروع»",
  },
  {
    id: "r3",
    target: "عطور الساحل",
    targetType: "أسرة منتجة",
    targetHref: "/producers/pr3",
    reason: "صورة مخالفة",
    reporter: "مستخدم #654",
    date: "قبل يومين",
    status: "resolved",
    message: "إحدى صور المنتجات تعرض علامة تجارية مسجّلة لشركة عطور عالمية بدون إذن.",
    content: "صورة منتج «عود فاخر» تظهر فيها عبوة تحمل شعار علامة تجارية عالمية مسجّلة.",
  },
];
